In [2]:
import torch
import numpy as np

In [4]:
data1 = np.array(10)
print(data1, data1.ndim, data1.shape)

10 0 ()


In [6]:
data2 = torch.FloatTensor([1,2])
print(data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])


In [7]:
data3 = torch.FloatTensor(3)
print(data3, data3.dim(),data3.shape)

tensor([0., 0., 0.]) 1 torch.Size([3])


In [8]:
data4 = torch.FloatTensor(3,2)
print(data4, data4.dim(),data4.shape)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]]) 2 torch.Size([3, 2])


In [10]:
data5 = torch.FloatTensor([[1,2], [3,4], [4,5]])
print(data5, data5.dim(),data5.shape)

tensor([[1., 2.],
        [3., 4.],
        [4., 5.]]) 2 torch.Size([3, 2])


In [11]:
data6 = torch.FloatTensor(3,2,1)
print(data6, data6.dim(),data6.shape)

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]],

        [[0.],
         [0.]]]) 3 torch.Size([3, 2, 1])


In [14]:
a = ['1','2','3','4','5','1']
b = ['1','4']
c = [1,2,3,4,5]
d = [2]
import collections

In [15]:
collections.Counter(c) - collections.Counter(d)

Counter({1: 1, 3: 1, 5: 1})

In [18]:
(set(c) & set(d))

{2, 4}

In [19]:
a = list(range(1,6))

In [20]:
a

[1, 2, 3, 4, 5]

In [21]:
a.remove(3)

In [22]:
a

[1, 2, 4, 5]